* Revised script to update the ID EEPROM. * Revised script to update the firmware of the Moitessier HAT. * Added script that is used to test the HAT during production.

diff --git a/eeprom_update_moitessier b/eeprom_update_moitessier
--- a/eeprom_update_moitessier
+++ b/eeprom_update_moitessier
@@ -5,16 +5,17 @@
 # Usage: sudo ./eeprom_update_moitesssier
 
 # script configuration
-configFile=/boot/config.txt                                 # the boot configuration file used by the Raspberry Pi
-overlayPath=/boot/overlays                                  # the path to the device tree overlay directory on the Raspberry Pi
+configFile=/boot/config.txt                                 # the boot configuration file used by the Raspberry Pi (absolute path)
+overlayPath=/boot/overlays                                  # the path to the device tree overlay directory on the Raspberry Pi (absolute path)
 moitessierDriverName=moitessier                             # the name of the Moitessier HAT driver module
-moitessierDriverPath=${moitessierDriverName}.ko             # the path of the Moitessier HAT driver module
-moitessierCtrlApp=../app/moitessier_ctrl/moitessier_ctrl    # the application used to control the Moitessier HAT
-moitessierDevice=/dev/moitessier.ctrl                       # the device used to write control commands to the Moitessier HAT
-moitessierDeviceTreeImage=moitessier.eep                    # the EEPROM image to write
-moitessierDeviceTree=moitessier.dtbo                        # the compiled device tree, this will be used as overlay
+moitessierDriverPath=${moitessierDriverName}.ko             # the path of the Moitessier HAT driver module (relative path)
+moitessierCtrlApp=../app/moitessier_ctrl/moitessier_ctrl    # the application used to control the Moitessier HAT (relative path)
+moitessierDevice=/dev/moitessier.ctrl                       # the device used to write control commands to the Moitessier HAT (absolute path)
+moitessierDeviceTreeImage=moitessier.eep                    # the EEPROM image to write (relative path)
+moitessierDeviceTree=moitessier.dtbo                        # the compiled device tree, this will be used as overlay (relative path)
+dump=dump.eep
 
-
+dir="`dirname \"$0\"`"
 
 dtparamValid=0
 dtoverlayValid=0
@@ -45,6 +46,40 @@ info()
     echo
 }
 
+help()
+{
+    echo
+    echo "******************************************************************************************"
+    echo "This script is used to flash the EEPROM of the Moitessier HAT."
+    echo       
+    echo "Available options:"
+    echo "    -n : If set the board will not reboot afterwards."
+    echo "    -k : If set the device tree overlay will be kept."
+    echo "******************************************************************************************"
+    echo
+}
+
+help
+
+nOption=0
+kOption=0
+
+while getopts 'nkh' option
+do
+    case $option in
+        n) nOption=1
+            ;;
+        k) kOption=1
+            ;;
+        h) exit 0
+            ;;
+        \?) echo
+            error "Invalid option."
+            exit 1
+            ;;
+    esac
+done
+
 if [ "$EUID" -ne 0 ]
 then 
     error "You must run this script with root privileges."
@@ -73,10 +108,10 @@ then
     sh -c "echo 'dtoverlay=moitessier' >> $configFile"
 fi
 
-cp ${moitessierDeviceTree} ${overlayPath}
+cp "${dir}/${moitessierDeviceTree}" ${overlayPath}
 if [ $? -ne 0 ]
 then
-    error "Copying device tree \"${moitessierDeviceTree}\" to \"${overlayPath}\" failed."
+    error "Copying device tree \"${dir}/${moitessierDeviceTree}\" to \"${overlayPath}\" failed."
     exit 1
 fi
 
@@ -105,42 +140,88 @@ then
     unload $moitessierDriverName
 fi
 
-insmod $moitessierDriverPath
+insmod "${dir}/$moitessierDriverPath"
 if [ $? -ne 0 ]
 then
     error "Could not load \"$moitessierDriverPath\"."
     exit 1
 fi
 
-./${moitessierCtrlApp} ${moitessierDevice} 6 0
+"${dir}/${moitessierCtrlApp}" ${moitessierDevice} 6 0
 if [ $? -ne 0 ]
 then
     error "Could not disable EEPROM write protection."
     exit 1
 fi
 
-./eepflash.sh -w -f=${moitessierDeviceTreeImage} -t=24c32 -d=0 -a=50 --force
+"${dir}/eepflash.sh" -w -f="${dir}/${moitessierDeviceTreeImage}" -t=24c32 -d=0 -a=50 --force
 if [ $? -ne 0 ]
 then
     error "Could not write EEPROM image."
     exit 1
 fi
 
+if [ -e "${dir}/${dump}" ]
+then
+    echo "WARNING: The dump file \"${dir}/${dump}\" already exists. It will be deleted."
+    rm "${dir}/${dump}"
+    if [ $? -ne 0 ]
+    then
+        error "Could not delete ${dir}/${dump}"
+        exit 1
+    fi
+fi
+
+"${dir}/eepflash.sh" -r -f="${dir}/${dump}" -t=24c32 -d=0 -a=50 --force
+if [ $? -ne 0 ]
+then
+    error "Could not read EEPROM image."
+    exit 1
+fi
+
+size=$(wc -c < "${dir}/${moitessierDeviceTreeImage}")
+cmp -n ${size} "${dir}/${moitessierDeviceTreeImage}" "${dir}/${dump}"
+if [ $? -ne 0 ]
+then
+    error "Verify failed."
+    exit 1
+fi
+
+rm "${dir}/${dump}"
+if [ $? -ne 0 ]
+then
+    error "Could not delete ${dir}/${dump}"
+    exit 1
+fi
 
 # if the EEPROM is written, we don't need to load the device tree from the overlay directory, as the relevant information
 # is directly loaded from the EEPROM
-sed -i '/dtoverlay=moitessier/d' ${configFile}
+if [ $kOption -eq 0 ]
+then
+    sed -i '/dtoverlay=moitessier/d' ${configFile}
+else
+    info "Device tree overlay not overwritten!!" 
+fi
 
 echo 
 echo "**************************************************************************************"
 echo "*                                                                                    *"
 echo "* EEPROM IMAGE WRITTEN SUCCESSFULLY!!!                                               *"
 echo "*                                                                                    *"
-echo "* Rebooting system...                                                                *"
-echo "*                                                                                    *"
+
+if [ $nOption -eq 0 ]
+then
+    echo "* Rebooting system...                                                                *"
+    echo "*                                                                                    *"    
+fi
+
 echo "**************************************************************************************"
 echo
 
-sleep 4
+if [ $nOption -eq 0 ]
+then
+    sleep 4
+    reboot 
+fi
 
-reboot 
+exit 0    
diff --git a/fw_update_moitessier b/fw_update_moitessier
--- a/fw_update_moitessier
+++ b/fw_update_moitessier
@@ -10,10 +10,10 @@
 # Usage: ./fw_update_moitessier -h
 
 moitessierDriverName=moitessier                                 # the name of the Moitessier HAT driver module
-moitessierDriverPath=moitessier.ko                              # the path of the Moitessier HAT driver module
-flasher=./stm32flash                                            # STM32 flasher (path/file name)
+moitessierDriverPath=moitessier.ko                              # the path of the Moitessier HAT driver module (relative path)
+flasher=stm32flash                                              # STM32 flasher (path/file name) (relative path)
 i2cDriverName=i2c_gpio_param                                    # I2C bit-banged driver module name    
-i2cDriverPath=i2c-gpio-param.ko                                 # I2C bit-banged driver module path
+i2cDriverPath=i2c-gpio-param.ko                                 # I2C bit-banged driver module path (relative path)
 i2cDeviceNr=5                                                   # the device number that should be assigned to the GPIO bit-banged bus
 i2cSdaPinNumber=2                                               # The GPIO pin number that should be used as SDA. If using the default I2C bus on the
                                                                 # Raspberry Pi, use pin 2.
@@ -22,7 +22,11 @@ i2cSclPinNumber=3                                               # The GPIO pin n
 repo=https://github.com/mr-rooney/moitessier-firmware.git       # repository holding the latest HAT firmware
 fwPath=fw                                                       # the path to store the firmware
 fwFileRemote=$fwPath/application.binary                         # path + file name of the firmware, if loaded from the remote repository
-blackList=fw_update_moitessier_black_list.txt                   # file that holds the processes/programms that need to be killed before the update can be executed
+blackList=fw_update_moitessier_black_list.txt                   # file that holds the processes/programms that need to be killed before the update can be executed (relative path)
+
+
+# calling path
+dir="`dirname \"$0\"`"
 
 unload()
 {
@@ -106,9 +110,9 @@ then
     exit 1
 fi
 
-if [ ! -e $flasher ]
+if [ ! -e "${dir}/$flasher" ]
 then
-    error "The flasher \"$flasher\" is missing."
+    error "The flasher \"${dir}/$flasher\" is missing."
     exit 1
 fi
 
@@ -177,58 +181,58 @@ fi
 # keep track about current i2c devices
 i2cDevicesBeforeLoad=$(ls /sys/class/i2c-dev)
 
-echo "INFO: Loading driver \"$i2cDriverPath\"."
-insmod $i2cDriverPath
+echo "INFO: Loading driver \"${dir}/$i2cDriverPath\"."
+insmod "${dir}/$i2cDriverPath" busid=${i2cDeviceNr} sda=${i2cSdaPinNumber} scl=${i2cSclPinNumber}
 if [ $? -ne 0 ]
 then
-    error "Could not load \"$i2cDriverPath\"."
+    error "Could not load \"${dir}/$i2cDriverPath\"."
     exit 1
 fi
 
-# we've loaded the bit-banged driver, so the i2c device list might have been changed
-i2cDevicesAfterLoad=$(ls /sys/class/i2c-dev)
-
-# convert the strings holding the i2c devices to an array, so we can process the individual devices
-i2cDevicesBeforeLoadList=($(echo $i2cDevicesBeforeLoad | tr " " "\n"))
-i2cDevicesAfterLoadList=($(echo $i2cDevicesAfterLoad | tr " " "\n"))
-
-# create an array, that holds the differences --> will hold the i2c devices that were added due to bit-banged driver loading
-i2cDevicesToDeleteList=()
-for i in "${i2cDevicesAfterLoadList[@]}"; do
-     skip=
-     for j in "${i2cDevicesBeforeLoadList[@]}"; do
-         [[ $i == $j ]] && { skip=1; break; }
-     done
-     [[ -n $skip ]] || i2cDevicesToDeleteList+=("$i")
-done
-declare -p i2cDevicesToDeleteList
-
-# remove the devices, so we can cleanly add them afterwards
-for i2cDev in "${i2cDevicesToDeleteList[@]}"
-do
-    echo "INFO: Deleting I2C device ${i2cDev}."
-    echo ${i2cDev##*-} > /sys/class/i2c-gpio/remove_bus
-    if [ $? -ne 0 ]
-    then
-        error "Could not delete I2C device ${i2cDev}."
-        exit 1
-    fi
-done        
-
-#if [ -e "/sys/class/i2c-dev/i2c-${i2cDeviceNr}" ]
-#then
-#    echo "INFO: Deleting I2C device."
-#    echo ${i2cDeviceNr} > /sys/class/i2c-gpio/remove_bus
-#fi
-
-echo "INFO: Creating I2C bus."
-echo ${i2cDeviceNr} ${i2cSdaPinNumber} ${i2cSclPinNumber} 2 100 > /sys/class/i2c-gpio/add_bus
-if [ $? -ne 0 ]
-then
-    error "Could not create I2C bus."
-    unload $i2cDriverName
-    exit 1
-fi  
+#### we've loaded the bit-banged driver, so the i2c device list might have been changed
+###i2cDevicesAfterLoad=$(ls /sys/class/i2c-dev)
+###
+#### convert the strings holding the i2c devices to an array, so we can process the individual devices
+###i2cDevicesBeforeLoadList=($(echo $i2cDevicesBeforeLoad | tr " " "\n"))
+###i2cDevicesAfterLoadList=($(echo $i2cDevicesAfterLoad | tr " " "\n"))
+###
+#### create an array, that holds the differences --> will hold the i2c devices that were added due to bit-banged driver loading
+###i2cDevicesToDeleteList=()
+###for i in "${i2cDevicesAfterLoadList[@]}"; do
+###     skip=
+###     for j in "${i2cDevicesBeforeLoadList[@]}"; do
+###         [[ $i == $j ]] && { skip=1; break; }
+###     done
+###     [[ -n $skip ]] || i2cDevicesToDeleteList+=("$i")
+###done
+###declare -p i2cDevicesToDeleteList
+###
+#### remove the devices, so we can cleanly add them afterwards
+###for i2cDev in "${i2cDevicesToDeleteList[@]}"
+###do
+###    echo "INFO: Deleting I2C device ${i2cDev}."
+###    echo ${i2cDev##*-} > /sys/class/i2c-gpio/remove_bus
+###    if [ $? -ne 0 ]
+###    then
+###        error "Could not delete I2C device ${i2cDev}."
+###        exit 1
+###    fi
+###done        
+###
+####if [ -e "/sys/class/i2c-dev/i2c-${i2cDeviceNr}" ]
+####then
+####    echo "INFO: Deleting I2C device."
+####    echo ${i2cDeviceNr} > /sys/class/i2c-gpio/remove_bus
+####fi
+###
+###echo "INFO: Creating I2C bus."
+###echo ${i2cDeviceNr} ${i2cSdaPinNumber} ${i2cSclPinNumber} 2 100 > /sys/class/i2c-gpio/add_bus
+###if [ $? -ne 0 ]
+###then
+###    error "Could not create I2C bus."
+###    unload $i2cDriverName
+###    exit 1
+###fi  
 
 # Check if OpenPlotter, and especially kplex, is running. If running, we need to stop it, otherwise loading the
 # driver for the Moitessier HAT fails as resource is busy.
@@ -247,7 +251,7 @@ while IFS='' read -r line || [[ -n "$line" ]]; do
     else
         echo "INFO: ${toKill} not running."
     fi
-done < "$blackList"
+done < "${dir}/${blackList}"
 
 lsm=$(lsmod | grep $moitessierDriverName)
 if [ $? -eq 0 ]
@@ -264,16 +268,16 @@ fi
 # delay
 secondsElapsed=0
 startTimestamp=$(date +%s)
-while [ $secondsElapsed -lt 4 ]
+while [ $secondsElapsed -lt 5 ]
 do
     printf "."
     sleep 0.2
     currentTimestamp=$(date +%s)
     secondsElapsed=$((currentTimestamp-startTimestamp))
 done
-
+echo
 echo "INFO: Flashing firmware."
-$flasher -R -i 17,-18,18:-17,18,-18,18 -w $fwFile -v -g 0x00 -a 0x41 /dev/i2c-${i2cDeviceNr}
+"${dir}/$flasher" -R -i 17,-18,18:-17,18,-18,18 -w $fwFile -v -g 0x00 -a 0x41 /dev/i2c-${i2cDeviceNr}
 if [ $? -ne 0 ]
 then
     error "Flashing firmware failed."
@@ -300,10 +304,10 @@ then
     shutdown now
 else
     unload $i2cDriverName
-    insmod $moitessierDriverPath
+    insmod "${dir}/$moitessierDriverPath"
     if [ $? -ne 0 ]
     then
-        error "Could not load \"$moitessierDriverPath\"."
+        error "Could not load \"${dir}/$moitessierDriverPath\"."
         exit 1
     fi   
 fi
