* Added support for I2C GPIO device detection. * Bug-fix: There is a bug in the official Raspberry Pi kernel version 4.9.118 that will prevent the Pi to boot if the overlay i2c-gpio is set in /boot/config.txt. For updating the system/kernel execute script bug_fix_kernel_4.19.118 in combination with the i2c-gpio.dtbo file in folder dtbo.

diff --git a/fw_update_moitessier b/fw_update_moitessier
--- a/fw_update_moitessier
+++ b/fw_update_moitessier
@@ -21,6 +21,8 @@ fwPath=fw                                                       # the path to st
 fwFileRemote=$fwPath/application.binary                         # path + file name of the firmware, if loaded from the remote repository
 blackList=fw_update_moitessier_black_list.txt                   # file that holds the processes/programms that need to be killed before the update can be executed (relative path)
 retries=5                                                       # number of retries before giving up the firmware update
+GET_I2C_GPIO_DEVICE_SCRIPT=get_i2c_gpio_device                  # name of the script to determine the I2C GPIO device used for firmware updates
+tmpFileI2C=i2c_dev.tmp                                          # file where I2C device is written to
 
 # calling path
 dir="`dirname \"$0\"`"
@@ -90,7 +92,8 @@ info()
     echo
 }
 
-pwd=$(pwd)
+#pwd=$(pwd)
+pwd="`dirname \"$0\"`"
 
 rOption=0
 sOption=0
@@ -161,6 +164,20 @@ then
     error "${configFile} has been changed. System will reboot. You need to call this script afterwards again."
     sleep 10
     reboot
+fi
+
+"${pwd}/${GET_I2C_GPIO_DEVICE_SCRIPT}"
+if [ $? -ne 0 ]
+then
+    error "Could not get I2C GPIO device"
+    exit 1
+fi
+
+read i2cDeviceNrAssigned < $tmpFileI2C
+if [ ${#i2cDeviceNrAssigned} -le 4 ]
+then 
+    error "No valid I2C GPIO device found"
+    exit 1
 fi
 
 if [ $rOption -eq 1 ]
@@ -263,7 +280,7 @@ do
         info "Flashing firmware."
         # GPIO18...nRESET pin
         # GPIO17...BOOT0 pin
-        "${dir}/$flasher" -R -i 18,,,17,,,-18,,,,,18,,:,,-17,,,18,,,-18,,,18 -w $fwFile -v -g 0x00 -a 0x41 /dev/i2c-${i2cDeviceNr}
+        "${dir}/$flasher" -R -i 18,,,17,,,-18,,,,,18,,:,,-17,,,18,,,-18,,,18 -w $fwFile -v -g 0x00 -a 0x41 /dev/${i2cDeviceNrAssigned}
         if [ $? -ne 0 ]
         then
             error "Flashing firmware failed."
diff --git a/production_test b/production_test
--- a/production_test
+++ b/production_test
@@ -16,7 +16,8 @@
 #   sudo moitessier/scripts/production_test -k -s -g 0 2>&1 | tee ~/Desktop/production_test.log
 
 flasher=../flasher/fw_update_moitessier
-
+GET_I2C_GPIO_DEVICE_SCRIPT=get_i2c_gpio_device                  # name of the script to determine the I2C GPIO device used for firmware updates
+tmpFileI2C=i2c_dev.tmp
 eepromFlasher=../device_tree/eeprom_update_moitessier           # the path to the EEPROM update script (relative path)
 sensorScript=../app/sensors/check_functionality                 # the path to the script used to check the sensor functionality (relative path)
 sensorFile=../app/sensors/sensValues.txt                        # The file where the sensor readouts should be stored
@@ -44,8 +45,6 @@ pressureRange=200                                               # actual range i
 dtparamI2CValid=0
 dtoverlayMoitessierValid=0
 dtoverlayI2CgpioValid=0
-
-bus=/dev/i2c-${i2cDeviceNr}    
 
 pwd="`dirname \"$0\"`"
 
@@ -199,7 +198,7 @@ results()
     then
         format=${FORMAT_YELLOW}
     fi
-    echo -e "RECEIVER                           ${format}${receiverFailed}${FORMAT_DEFAULT}"
+    echo -e "RECEIVER                           ${format}${receiverFailed} (A: ${ais1Cnt}, B: ${ais2Cnt})${FORMAT_DEFAULT}"
     
     format=${FORMAT_RED}
     if [ "${gnssFixFailed}" == "${TEST_OK}" ]
@@ -439,6 +438,22 @@ then
     sleep 4
     reboot
 fi
+
+"${pwd}/${GET_I2C_GPIO_DEVICE_SCRIPT}"
+if [ $? -ne 0 ]
+then
+    error "Could not get I2C GPIO device"
+    exit 1
+fi
+
+read i2cDeviceNrAssigned < $tmpFileI2C
+if [ ${#i2cDeviceNrAssigned} -le 4 ]
+then 
+    error "No valid I2C GPIO device found"
+    exit 1
+fi
+
+bus=/dev/${i2cDeviceNrAssigned}  
 
 # check the sensors
 "${pwd}/${sensorScript}" -i ${bus} -c ${sensorIterations} --mpu --press --cpu -s -t ${temperature} -r ${temperatureRange} -p ${pressure} -n ${pressureRange}
