* Extended black list. * Revised update script. Slightly updated GPIO sequence.

diff --git a/fw_update_moitessier b/fw_update_moitessier
--- a/fw_update_moitessier
+++ b/fw_update_moitessier
@@ -23,7 +23,7 @@ repo=https://github.com/mr-rooney/moitessier-firmware.git       # repository hol
 fwPath=fw                                                       # the path to store the firmware
 fwFileRemote=$fwPath/application.binary                         # path + file name of the firmware, if loaded from the remote repository
 blackList=fw_update_moitessier_black_list.txt                   # file that holds the processes/programms that need to be killed before the update can be executed (relative path)
-
+retries=5                                                       # number of retries before giving up the firmware update
 
 # calling path
 dir="`dirname \"$0\"`"
@@ -171,145 +171,181 @@ echo "The firmware file \"${fwFile}\" is used for the update"
 echo "**************************************************************************************"
 echo 
 
-lsm=$(lsmod | grep $i2cDriverName)
-if [ $? -eq 0 ]
-then
-    echo "WARNING: Module \"$i2cDriverName\" is loaded, we will unload and reload afterwards."
-    unload $i2cDriverName
-fi
-
-# keep track about current i2c devices
-i2cDevicesBeforeLoad=$(ls /sys/class/i2c-dev)
-
-echo "INFO: Loading driver \"${dir}/$i2cDriverPath\"."
-insmod "${dir}/$i2cDriverPath" busid=${i2cDeviceNr} sda=${i2cSdaPinNumber} scl=${i2cSclPinNumber}
-if [ $? -ne 0 ]
-then
-    error "Could not load \"${dir}/$i2cDriverPath\"."
-    exit 1
-fi
-
-#### we've loaded the bit-banged driver, so the i2c device list might have been changed
-###i2cDevicesAfterLoad=$(ls /sys/class/i2c-dev)
-###
-#### convert the strings holding the i2c devices to an array, so we can process the individual devices
-###i2cDevicesBeforeLoadList=($(echo $i2cDevicesBeforeLoad | tr " " "\n"))
-###i2cDevicesAfterLoadList=($(echo $i2cDevicesAfterLoad | tr " " "\n"))
-###
-#### create an array, that holds the differences --> will hold the i2c devices that were added due to bit-banged driver loading
-###i2cDevicesToDeleteList=()
-###for i in "${i2cDevicesAfterLoadList[@]}"; do
-###     skip=
-###     for j in "${i2cDevicesBeforeLoadList[@]}"; do
-###         [[ $i == $j ]] && { skip=1; break; }
-###     done
-###     [[ -n $skip ]] || i2cDevicesToDeleteList+=("$i")
-###done
-###declare -p i2cDevicesToDeleteList
-###
-#### remove the devices, so we can cleanly add them afterwards
-###for i2cDev in "${i2cDevicesToDeleteList[@]}"
-###do
-###    echo "INFO: Deleting I2C device ${i2cDev}."
-###    echo ${i2cDev##*-} > /sys/class/i2c-gpio/remove_bus
-###    if [ $? -ne 0 ]
-###    then
-###        error "Could not delete I2C device ${i2cDev}."
-###        exit 1
-###    fi
-###done        
-###
-####if [ -e "/sys/class/i2c-dev/i2c-${i2cDeviceNr}" ]
-####then
-####    echo "INFO: Deleting I2C device."
-####    echo ${i2cDeviceNr} > /sys/class/i2c-gpio/remove_bus
-####fi
-###
-###echo "INFO: Creating I2C bus."
-###echo ${i2cDeviceNr} ${i2cSdaPinNumber} ${i2cSclPinNumber} 2 100 > /sys/class/i2c-gpio/add_bus
-###if [ $? -ne 0 ]
-###then
-###    error "Could not create I2C bus."
-###    unload $i2cDriverName
-###    exit 1
-###fi  
-
-# Check if OpenPlotter, and especially kplex, is running. If running, we need to stop it, otherwise loading the
-# driver for the Moitessier HAT fails as resource is busy.
-# The processes/programms to kill are specified in the black list file
-echo "INFO: Terminating running processes..."
-while IFS='' read -r line || [[ -n "$line" ]]; do
-    toKill="$line"
-    # we need to replace carriage return and line feed
-    toKill=$(echo ${toKill} | tr -d '\n','\r')
+for((ry = 0; ry < $retries; ry++))
+do
+    errorOccured=false
     
-    pid=$(pidof ${toKill})
+    lsm=$(lsmod | grep $i2cDriverName)
     if [ $? -eq 0 ]
     then
-        echo "INFO: Killing process ${toKill}."
-        pkill ${toKill}
-    else
-        echo "INFO: ${toKill} not running."
+        echo "WARNING: Module \"$i2cDriverName\" is loaded, we will unload and reload afterwards."
+        unload $i2cDriverName
     fi
-done < "${dir}/${blackList}"
 
-lsm=$(lsmod | grep $moitessierDriverName)
-if [ $? -eq 0 ]
-then
-    echo "WARNING: Module \"$moitessierDriverName\" is loaded, we will unload to gain access to the required GPIO pins."
-    unload $moitessierDriverName
+    # keep track about current i2c devices
+    i2cDevicesBeforeLoad=$(ls /sys/class/i2c-dev)
+
+    echo "INFO: Loading driver \"${dir}/$i2cDriverPath\"."
+    insmod "${dir}/$i2cDriverPath" busid=${i2cDeviceNr} sda=${i2cSdaPinNumber} scl=${i2cSclPinNumber}
     if [ $? -ne 0 ]
     then
-        error "Could not unload \"$moitessierDriverName\""
-        exit 1
-    fi  
-fi 
+        error "Could not load \"${dir}/$i2cDriverPath\"."
+        #exit 1
+        errorOccured=true
+    fi
 
-# delay
-secondsElapsed=0
-startTimestamp=$(date +%s)
-while [ $secondsElapsed -lt 5 ]
-do
-    printf "."
-    sleep 0.2
-    currentTimestamp=$(date +%s)
-    secondsElapsed=$((currentTimestamp-startTimestamp))
+    #### we've loaded the bit-banged driver, so the i2c device list might have been changed
+    ###i2cDevicesAfterLoad=$(ls /sys/class/i2c-dev)
+    ###
+    #### convert the strings holding the i2c devices to an array, so we can process the individual devices
+    ###i2cDevicesBeforeLoadList=($(echo $i2cDevicesBeforeLoad | tr " " "\n"))
+    ###i2cDevicesAfterLoadList=($(echo $i2cDevicesAfterLoad | tr " " "\n"))
+    ###
+    #### create an array, that holds the differences --> will hold the i2c devices that were added due to bit-banged driver loading
+    ###i2cDevicesToDeleteList=()
+    ###for i in "${i2cDevicesAfterLoadList[@]}"; do
+    ###     skip=
+    ###     for j in "${i2cDevicesBeforeLoadList[@]}"; do
+    ###         [[ $i == $j ]] && { skip=1; break; }
+    ###     done
+    ###     [[ -n $skip ]] || i2cDevicesToDeleteList+=("$i")
+    ###done
+    ###declare -p i2cDevicesToDeleteList
+    ###
+    #### remove the devices, so we can cleanly add them afterwards
+    ###for i2cDev in "${i2cDevicesToDeleteList[@]}"
+    ###do
+    ###    echo "INFO: Deleting I2C device ${i2cDev}."
+    ###    echo ${i2cDev##*-} > /sys/class/i2c-gpio/remove_bus
+    ###    if [ $? -ne 0 ]
+    ###    then
+    ###        error "Could not delete I2C device ${i2cDev}."
+    ###        exit 1
+    ###    fi
+    ###done        
+    ###
+    ####if [ -e "/sys/class/i2c-dev/i2c-${i2cDeviceNr}" ]
+    ####then
+    ####    echo "INFO: Deleting I2C device."
+    ####    echo ${i2cDeviceNr} > /sys/class/i2c-gpio/remove_bus
+    ####fi
+    ###
+    ###echo "INFO: Creating I2C bus."
+    ###echo ${i2cDeviceNr} ${i2cSdaPinNumber} ${i2cSclPinNumber} 2 100 > /sys/class/i2c-gpio/add_bus
+    ###if [ $? -ne 0 ]
+    ###then
+    ###    error "Could not create I2C bus."
+    ###    unload $i2cDriverName
+    ###    exit 1
+    ###fi  
+
+    if [ "$errorOccured" = false ]
+    then
+        # Check if OpenPlotter, and especially kplex, is running. If running, we need to stop it, otherwise loading the
+        # driver for the Moitessier HAT fails as resource is busy.
+        # The processes/programms to kill are specified in the black list file
+        echo "INFO: Terminating running processes..."
+        while IFS='' read -r line || [[ -n "$line" ]]; do
+            toKill="$line"
+            # we need to replace carriage return and line feed
+            toKill=$(echo ${toKill} | tr -d '\n','\r')
+            
+            pid=$(pidof ${toKill})
+            if [ $? -eq 0 ]
+            then
+                echo "INFO: Killing process ${toKill}."
+                pkill ${toKill}
+            else
+                echo "INFO: ${toKill} not running."
+            fi
+        done < "${dir}/${blackList}"
+
+        lsm=$(lsmod | grep $moitessierDriverName)
+        if [ $? -eq 0 ]
+        then
+            echo "WARNING: Module \"$moitessierDriverName\" is loaded, we will unload to gain access to the required GPIO pins."
+            unload $moitessierDriverName
+            if [ $? -ne 0 ]
+            then
+                error "Could not unload \"$moitessierDriverName\""
+                #exit 1
+                errorOccured=true
+            fi  
+        fi 
+    fi
+
+    if [ "$errorOccured" = false ]
+    then
+        # delay
+        secondsElapsed=0
+        startTimestamp=$(date +%s)
+        while [ $secondsElapsed -lt 8 ]
+        do
+            printf "."
+            sleep 0.2
+            currentTimestamp=$(date +%s)
+            secondsElapsed=$((currentTimestamp-startTimestamp))
+        done
+        echo
+        echo "INFO: Flashing firmware."
+        # GPIO18...nRESET pin
+        # GPIO17...BOOT0 pin
+        "${dir}/$flasher" -R -i 18,,,17,,,-18,,,,,18,,:,,-17,,,18,,,-18,,,18 -w $fwFile -v -g 0x00 -a 0x41 /dev/i2c-${i2cDeviceNr}
+        if [ $? -ne 0 ]
+        then
+            error "Flashing firmware failed."
+            unload $i2cDriverName
+            #exit 1
+            errorOccured=true
+        fi   
+    fi
+    
+    if [ "$errorOccured" = false ]
+    then
+        break;
+    else
+        error "An error occured, we will retry."
+    fi
 done
-echo
-echo "INFO: Flashing firmware."
-"${dir}/$flasher" -R -i 17,-18,18:-17,18,-18,18 -w $fwFile -v -g 0x00 -a 0x41 /dev/i2c-${i2cDeviceNr}
-if [ $? -ne 0 ]
-then
-    error "Flashing firmware failed."
-    unload $i2cDriverName
-    exit 1
-fi   
 
-echo 
-echo "**************************************************************************************"
-echo "*                                                                                    *"
-echo "* FIRMWARE UPDATE SUCCESSFULL!!!                                                     *"
-echo "*                                                                                    *"
-if [ $fOption == "1" ]
+if [ "$errorOccured" = false ]
 then
-echo "* Shutting down system. YOU NEED TO UNPLUG AND REPLUG THE POWER SUPPLY AFTERWARDS!!! *"
-echo "*                                                                                    *"
-fi
-echo "**************************************************************************************"
-echo 
-
-if [ $fOption == "1" ]
-then
-    sleep 4
-    shutdown now
-else
-    unload $i2cDriverName
-    insmod "${dir}/$moitessierDriverPath"
-    if [ $? -ne 0 ]
+    echo 
+    echo "**************************************************************************************"
+    echo "*                                                                                    *"
+    echo "* FIRMWARE UPDATE SUCCESSFULL!!!                                                     *"
+    echo "*                                                                                    *"
+    if [ $fOption == "1" ]
     then
-        error "Could not load \"${dir}/$moitessierDriverPath\"."
-        exit 1
-    fi   
+    echo "* Shutting down system. YOU NEED TO UNPLUG AND REPLUG THE POWER SUPPLY AFTERWARDS!!! *"
+    echo "*                                                                                    *"
+    fi
+    echo "**************************************************************************************"
+    echo
+
+    if [ $fOption == "1" ]
+    then
+        sleep 4
+        shutdown now
+    else
+        unload $i2cDriverName
+        insmod "${dir}/$moitessierDriverPath"
+        if [ $? -ne 0 ]
+        then
+            error "Could not load \"${dir}/$moitessierDriverPath\"."
+            exit 1
+        fi   
+    fi
+else
+    echo 
+    echo "**************************************************************************************"
+    echo "*                                                                                    *"
+    echo "* FIRMWARE UPDATE FAILED!!!                                                          *"
+    echo "*                                                                                    *"
+    echo "**************************************************************************************"
+    echo
+    
+    exit 1
 fi
 
 exit 0
