* Added error check related to unloading the Moitessier kernel module during firmware update. * Improved the script to load the driver by checking if the Moitessier HAT is available at all. Fixed the owner/access mode issue, that doesn't succeeded all the time.

diff --git a/fw_update_moitessier b/fw_update_moitessier
--- a/fw_update_moitessier
+++ b/fw_update_moitessier
@@ -4,7 +4,7 @@
 # The latest firmware will be loaded automatically form an online repository.
 # 
 # Ensure that you have the I2C module and the flashing tool compiled (see 
-# https://github.com/mr-rooney/nav.HAT for further information). You might
+# https://github.com/mr-rooney/moitessier for further information). You might
 # need to change the paths below.
 #
 # Usage: ./fw_update_moitessier -h
@@ -244,6 +244,11 @@ if [ $? -eq 0 ]
 then
     echo "WARNING: Module \"$moitessierDriverName\" is loaded, we will unload to gain access to the required GPIO pins."
     unload $moitessierDriverName
+    if [ $? -ne 0 ]
+    then
+        error "Could not unload \"$moitessierDriverName\""
+        exit 1
+    fi  
 fi 
 
 
diff --git a/load_driver_moitessier b/load_driver_moitessier
--- a/load_driver_moitessier
+++ b/load_driver_moitessier
@@ -20,10 +20,25 @@
 # You might need to change the path to the driver
 driverPath=/home/pi/moitessier/modules/moitessier.ko
 
-
+# The device file used for the TTY interface
 ttyDev=/dev/moitessier.tty
 
+# Path to device tree related information
+hatDevTree=/proc/device-tree/soc/spi@7e204000/moitessier@0/name
+
 start() {
+    hatName=$(cat ${hatDevTree})
+    if [ $? -ne 0 ]
+    then
+        echo "INFO: Moitessier HAT not available" > /dev/kmsg
+        exit 1
+    fi
+    
+    if [[ $hatName != *"moitessier"* ]]; then
+        echo "INFO: Moitessier HAT not available" > /dev/kmsg
+        exit 1
+    fi
+   
     echo "Loading $driverPath" > /dev/kmsg
     insmod $driverPath
     if [ $? -ne 0 ]
@@ -31,11 +46,23 @@ start() {
         echo "ERROR: Could not load $driverPath." > /dev/kmsg
         exit 1
     fi
+    # we need to sleep a while otherwise changing owner and access mode fails.
+    sleep 3
     chown pi:pi $ttyDev
     if [ $? -ne 0 ]
     then
         echo "ERROR: Could not set owner for $ttyDev. You might need super user rights to access the device." > /dev/kmsg
         exit 1
+    else
+        echo "Setting owner for $ttyDev." > /dev/kmsg
+    fi
+    chmod 666 $ttyDev
+    if [ $? -ne 0 ]
+    then
+        echo "ERROR: Could not set access mode for $ttyDev. You might need super user rights to access the device." > /dev/kmsg
+        exit 1
+    else
+        echo "Setting access mode for $ttyDev." > /dev/kmsg
     fi
 }
 stop() {
