* I2C GPIO device detection modified. Under certain circumstances it does not work as expected. Different kernel versions use a different naming convention for the interface that causes the algorithm to fail. The new algorithm not only checks, if the bus is available, it also verifies, if an I2C chip (in our case the MPU sensor with address 0x68) is present on the bus. In general the hardware I2C bus is assigned to /dev/i2c-1 and any GPIO software based I2C bus is assigned to an higher device number, e.g. /dev/i2c-3. This mainly depends on the system and the configuration in /boot/config.txt. The I2C GPIO device detection will always use the I2C bus with the highest number, if any assigned. * The kernel bug fix script will not abort, if any of the system update/upgrade commands will fail, otherwise the system might get unbootable.

diff --git a/get_i2c_gpio_device b/get_i2c_gpio_device
--- a/get_i2c_gpio_device
+++ b/get_i2c_gpio_device
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 tmpFile=i2c_dev.tmp
+defaultI2Cdev="i2c-3"
 
 FORMAT_RED="\e[1;31m"
 FORMAT_YELLOW="\e[1;93m"
@@ -19,27 +20,53 @@ info()
 
 info "Determining I2C GPIO device"
 
-devices=$(i2cdetect -l | grep "i2c@")
-dev=$(echo $devices | cut -d ' ' -f 1)
+dev=$(i2cdetect -l)
+#replace tab and line feed character with space
+dev1=${dev//$'\t'/ }
+devices=${dev1//$'\n'/ }
 
-if [ ! -e $tmpFile ]
-then
-    touch $tmpFile
-    if [ $? -ne 0 ]
-    then
-        error "Could not create file \"${tmpFile}\" to write I2C GPIO device"
-        exit 1
-    fi   
-fi
+declare -a deviceList
+k=0
 
-echo $dev > $tmpFile
+IFS=' ' # space is set as delimiter
+read -ra ADDR <<< "$devices"
+for i in "${ADDR[@]}"
+do 
+    # only use devices that are named i2c-x
+    if [[ $i == *"i2c-"* ]]; then
+        deviceList[$k]=$i
+        k=$k+1
+    fi
+done
+
+# check on which bus the sensors of the HAT are available
+# 0x68 is the address of the MPU sensor
+for i in "${deviceList[@]}"
+do 
+    # i2c-
+    dev=$(echo $i | cut -c5-)
+    i2cdetect -y $dev 0x68 0x68 | grep 68 > /dev/null
+    if [ $? -eq 0 ]
+    then    
+        echo $i > $tmpFile
+        if [ $? -ne 0 ]
+        then
+            error "Could not write I2C GPIO device to file \"${tmpFile}\""
+            exit 1
+        fi
+
+        info "I2C GPIO device: ${dev}"
+        
+        exit 0        
+    fi        
+done
+
+echo $i > $tmpFile
 if [ $? -ne 0 ]
 then
     error "Could not write I2C GPIO device to file \"${tmpFile}\""
     exit 1
 fi
+info "I2C GPIO device (probing failed, using default): ${defaultI2Cdev}"
 
-info "I2C GPIO device: ${dev}"
-
-exit $?
-
+exit 1
